server:
  port: 8081

# 나자신은 등록하지 않음
eureka.client.register-with-eureka: false
# 마이크로 서비스 인스턴스 목록을 로컬에 캐시할 것인지의 여부
eureka.client.fetch-registry: false
## 아래 설정이 없으면 다음 에러
eureka.client.service-url.defaultZone: http://localhost:${server.port}/eureka/

external-api:
  #  user:
  #    url: http://localhost:8081
  auth:
    url: http://localhost:8082/auth
  order:
    url: http://localhost:8091/order
  pay:
    url: http://localhost:8092

logging:
  level:
    com.spring.cloud: DEBUG

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true